import AdminSettingmodel from '../../models/Settings/Admin.js'
import { UserModel } from '../../models/Administration/Authorization/index.js'
import { hashPassword } from '../../services/authServices.js';


export const StudentSettingInfo=async(req,res)=>{
   try {
     const {userId}=req.body
    
    const data = await AdminSettingmodel.findOne({userId})

     if(!data){
         res.json({status:'failed'})
      }
      res.status(200).json({status:'done',data})

   } catch (error) {
     console.log("student setting error", error)
   }
}

export const notificationSetting = async(req,res)=>{
    try {
      const {
        AnnouncementNotifications,
       SubscriptionExpiryAlerts,
        NewTicketAlerts,
        ActivityLogs,
        CourseContentNotifications,   
        userId
      }=req.body

      const data = await AdminSettingmodel.updateOne({userId},
        {notification:{ AnnouncementNotifications,
       SubscriptionExpiryAlerts,
        NewTicketAlerts,
        ActivityLogs,
        CourseContentNotifications, }})
      if(!data){
         res.json({status:'failed'})
      }
      res.status(200).json({status:'done'})
    } catch (error) {
      console.log("notiffy admin",error)
      res.json({status:"failed"})
    }
}

export const UpdatePersonal=async(req,res)=>{
 try {
    const {userId,name,email,contact,image}=req.body
    const data = await AdminSettingmodel.findOneAndUpdate({userId},{name,email,contact,image},{new:true}).populate('Instituteuserlist')
      if(!data){
         res.json({status:'failed'})
      }
      res.status(200).json({status:'done',data})
 } catch (error) {
  console.log("admin setting error", error)
 }
}

export const ReportSetting=async(req,res)=>{
    try {
        const {AutoReport,ReportMethod,userId} = req.body
        const data = await AdminSettingmodel.updateOne({userId},{ AutoGeneratedReports:AutoReport,CustomizeReportFrequency:ReportMethod})
          if(!data){
         res.json({status:'failed'})
      }
      res.status(200).json({status:'done',data})
    } catch (error) {
        console.log("admin setting error", error)
    }
}

export const PrivacySecurity =async(req,res)=>{
    try {
        const {email,password}=req.body
        const hashPassword = hashPassword(password)
        const data = await UserModel.updateOne({email},{password: hashedPassword})
         if(!data){
         res.json({status:'failed'})
      }
      res.status(200).json({status:'done'})
    } catch (error) {
        console.log("admin setting error", error)
    }
}