import mongoose from "mongoose";

const AdminSettingsSchema = new mongoose.Schema({
    uuid:{
        type:String,
        unique:true,
     },
    userId:{
        type:Schema.Types.ObjectId,
        ref:"non-teachingstaff_login",
        required:true
     },
     InstituteId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"institute"
     },
    notification:{
      AnnouncementNotifications:{type:Boolean,default:true},
      SubscriptionExpiryAlerts :{type:Boolean,default:true},
      NewTicketAlerts:{type:Boolean,default:true},
      ActivityLogs:{type:Boolean,default:true},
      CommunityMessages:{type:Boolean,default:true},
      CourseContentNotifications:{type:Boolean,default:true},
    },
    Reports:{
      AutoGeneratedReports:{type:Boolean,default:true},
      CustomizeReportFrequency:{type:String, enum:["Daily","Weekly","Monthly"],default:"Monthly"},
    }
     
})

const AdminSettingmodel= mongoose.model("AdminSettingmodel",AdminSettingsSchema)

export default AdminSettingmodel
